# .github/workflows/ci-cd.yml
name: CI/CD

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: List test files
        run: ls -R tests/
        
      - name: Test with pytest
        run: pytest -v test/

      - name: Build and publish package
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          python setup.py sdist bdist_wheel
          pip install twine
          twine upload --repository pypi dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
